[tool.poetry]
name = "minlog"
version = "0.1.0"
description = ""
authors = ["redthing1 <redthing1@alt.icu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
rich = "^13.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
